### ISSUE TITLE
Timestamp field?

### ISSUE THREAD

**Issue by robin13** [patw/ElasticSensorDump#1]
First off - VERY cool project!  Ideas exploding right now what can be done with this! :)

How to display as timeseries data in Kibana?  The field `Time` is created as a long number, but a date would be better - this should work:

```
        "Time": {
          "type":   "date",
          "format": "epoch_millis"
        }
```

**Comment by patw** [comment]
I'm thinking of creating the index with that minimal schema on config.  I'll be adding some todos soon.

**Comment by patw** [comment]
Fixed this issue in the most recent version.  ES can auto detect dates if they're in the correct format.  SLOWEST DEVELOPER EVAR!! ;)
