### ISSUE TITLE
[Feature request] Enable date pattern indexing

### ISSUE THREAD

**Issue by GlenRSmith** [patw/ElasticSensorDump#19]
It would be nice to have the ability to specify daily/weekly/monthly indices.

(Could be worked around by running a cron job from some host in the meantime - create index and move alias, thought this wouldn't assure entries actually end up in the correct index)

**Comment by patw** [comment]
So maybe tagging the index name during the sensor dump with something like -YYYYDDMM?

**Comment by GlenRSmith** [comment]
Yeah, that would be cool.

**Comment by patw** [comment]
Update on google play store shortly.
