### ISSUE TITLE
Logging interval possible?

### ISSUE THREAD

**Issue by robin13** [patw/ElasticSensorDump#3]
My cluster couldn't keep up with the volume of data... would it be possible to define the logging interval in the settings too?

**Comment by patw** [comment]
I think batch posting will help here, the code is doing a regular doc by doc post right now which isn't very efficient.  Otherwise a slider to indicate how often to refresh the data might be an option.

**Comment by patw** [comment]
Adjustable slider is coming, but right now it's doing every 250ms, should not swamp any ES single node or cluster.

**Comment by patw** [comment]
Adjustable interval is implemented and will show up in the next Google Play release.
